// <auto-generated />
namespace DAB4_new.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Traderinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Traderinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201805251755119_Traderinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
